name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:

  test:
    name: Playwright project
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false 

      matrix:
        include:
          - project: conduit
            browser: chormium
            base_url: https://demo.realworld.show/
          - project: the-internet
            browser: chromium
            base_url: https://the-internet.herokuapp.com/

    steps:
    - name: Chechout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    - name: Install dependencies
      run: npm ci
  
    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - name: Install Playwright Browsers (cache miss)
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install-deps ${{ matrix.browser }}

    - name: Run Playwright tests
      run: npx playwright test --project=${{ matrix.project }}
      env:
        BASE_URL: ${{ matrix.base_url }}

    - name: Upload Playwright HTML report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.project }}
        path: playwright-report/
        retention-days: 14

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results-${{ matrix.project }}
        path: test-results/
        retention-days: 14
    
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-results-${{ matrix.project }}
        path: allure-results/
        retention-days: 14
